version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
    - 17.0.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.8
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
    - 7.23.2
  - dependency-name: styled-icons
    versions:
    - 10.30.0
    - 10.31.0
    - 10.32.0
    - 10.33.0
  - dependency-name: husky
    versions:
    - 5.2.0
    - 6.0.0
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
  - dependency-name: next-pwa
    versions:
    - 5.0.6
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.21
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
    - 10.5.4
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ini
    versions:
    - 1.3.8
